version: '3.5'
services:
  ingress:
    image: nginx:latest
    volumes:
      - './deployment/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '8877:80'
    depends_on:
      - frontend
      - backend
  frontend:
    image: rafaelottersberg/react-mui-flask-webapp-frontend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - './build:/usr/share/nginx/html'
      - './backend/storage/images/website:/usr/share/nginx/html/static/web-photos'
      - './backend/storage/images/check:/usr/share/nginx/html/static/web-photos-check'
  backend:
    image: rafaelottersberg/react-mui-flask-webapp-backend
    build:
      dockerfile: Dockerfile
      context: backend
    volumes:
      - './backend/api:/app/api'
      - './backend/migrations:/app/migrations'
      - './backend/storage:/app/storage'
    env_file:
      - './secrets.env'
    environment:
      IMAGE_SIZE: 800
      IMAGE_QUALITY: 85
