name: Build and publish Docker image for backend

on:
  push:
    branches:
      - master
      - release

jobs:
  dockerize:
    name: Create docker image for backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image (latest)
        if: github.event.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/backend:latest
      - name: Build container image (stable)
        if: github.event.ref == 'refs/heads/release'
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/backend:stable
